-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  rbac_user_roles

CREATE TABLE IF NOT EXISTS rbac_user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  tenant_id BIGINT NULL,                          -- optional multitenant scope
  scope VARCHAR(120) NULL,                        -- e.g. 'project:123'
  status TEXT NOT NULL DEFAULT 'active',          -- 'active','revoked','expired'
  granted_by BIGINT NULL,
  granted_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_rbac_user_roles UNIQUE (user_id, role_id, tenant_id, scope),
  CONSTRAINT chk_rbac_user_roles_status CHECK (status IN ('active','revoked','expired'))
);
